// Groups every site text by where it appears, for the admin text editor.
// Keys are the English source strings used in the components. When a text
// is added to the site, add it here as well; tests/site-texts.spec.ts
// checks that this list and the translations stay complete.
export const textSections: { title: string; note?: string; keys: string[] }[] =
  [
    {
      title: "Site-wide: navigation, footer and search description",
      note: "Keep menu labels short: longer ones may not fit in the top menu on smaller screens.",
      keys: [
        "Logistic Hub home",
        "Main navigation",
        "Cars from China",
        "For dealers",
        "Fee calculator",
        "Let’s talk",
        "Close navigation",
        "Open navigation",
        "Mobile navigation",
        "Language",
        "Skip to content",
        "Back to home",
        "Start an inquiry",
        "Founded in Tbilisi, Georgia.",
        "Connected to a world of vehicles.",
        "USA · Europe · China",
        "Photos outside car listings are illustrative.",
        "Vehicle sourcing from the USA, Europe and China. Expert inspection, auction access and delivery support for private buyers and automotive dealers in Tbilisi.",
      ],
    },
    {
      title: "Home: opening",
      keys: [
        "A dark Porsche travelling on an open road",
        "YOUR NEXT CAR.",
        "A WORLD OF",
        "POSSIBILITIES.",
        "Vehicles from the USA, Europe and China.",
        "Expert support from selection to delivery.",
        "Find a vehicle",
        "Discover the process",
        "Your choice. Our responsibility.",
        "BASED IN TBILISI. THINKING BEYOND BORDERS.",
        "A world of choice.",
        "One point of contact.",
        "EUROPE",
        "CHINA",
      ],
    },
    {
      title: "Home: services",
      keys: [
        "You choose the vehicle.",
        "We connect the dots.",
        "From your first shortlist to the final handover, we bring expertise and clarity to every step.",
        "A silver sports car in an automotive showroom",
        "For private buyers",
        "A car that’s right for you.",
        "A team that’s on your side.",
        "Start a private buyer inquiry",
        "More confidence.",
        "Less guesswork.",
        "Buying a vehicle abroad should feel exciting. We help you understand the options and make informed decisions.",
        "Vehicle sourcing tailored to your needs",
        "Expert review before auction bidding",
        "History checks, including Carfax reports",
        "Documentation and delivery support",
        "Let’s find your vehicle",
        "Buying for your business?",
        "Your next opportunity starts here.",
        "Explore dealer services",
      ],
    },
    {
      title: "Home: latest cars",
      keys: [
        "Ready to go.",
        "Cars from China.",
        "Recently selected offers, with prices and delivery to Tbilisi.",
        "See all cars",
      ],
    },
    {
      title: "Home: sourcing regions",
      keys: [
        "USA",
        "Europe",
        "China",
        "More choice. Expert eyes on every lot.",
        "Explore trusted US auctions with a team that reviews the vehicle’s history, documentation and available information before bidding.",
        "Your European search starts here.",
        "Tell us what you are looking for. Our team helps you source a vehicle from Europe and coordinates documentation and delivery.",
        "Vehicle sourcing · Documentation · Delivery",
        "A new market. A familiar level of care.",
        "Explore vehicle sourcing from China with professional support, clear communication and coordinated logistics through to delivery.",
        "Vehicle selection · Logistics · Ongoing updates",
        "Three regions.",
        "One trusted team.",
        "Look beyond borders. We’ll take care of the journey.",
        "Vehicle sourcing region",
        "Tbilisi, GE",
        "Explore",
      ],
    },
    {
      title: "Home: process",
      keys: [
        "Vehicle selection",
        "Tell us what you’re looking for, or send us a lot you already have in mind.",
        "Expert inspection",
        "We review the available information, vehicle history and documentation before bidding.",
        "Auction bidding",
        "Only after expert approval do we move forward with bidding on your selected vehicle.",
        "Documentation & logistics",
        "Our team coordinates the paperwork and delivery arrangements with Lion Trans.",
        "Updates at every stage",
        "Stay informed throughout the process, with clear communication from our team.",
        "Vehicle delivery",
        "Support continues until your vehicle is received. Your choice becomes your next drive.",
        "A clear road.",
        "From start to finish.",
        "Six steps. One team by your side.",
        "We handle the details and keep you in the loop.",
        "Expert approval comes first.",
        "We review the lot before bidding to help reduce risks and avoid unsuitable vehicles.",
      ],
    },
    {
      title: "Home: about and auctions",
      keys: [
        "Built on experience.",
        "Driven by responsibility.",
        "Logistic Hub was founded in Tbilisi by three partners with more than 15 years of experience in the automotive industry.",
        "We bring that hands-on knowledge to every vehicle search. As an independent company, we put transparency, personal support and consistent communication at the heart of what we do.",
        "Meet your next automotive partner",
        "years of automotive experience",
        "among our founders",
        "Logistics in trusted hands",
        "Our logistics partner, helping connect your vehicle’s origin to its destination.",
        "Dealer access to leading US auctions",
        "Find out more",
      ],
    },
    {
      title: "Home: questions",
      keys: [
        "A few things",
        "worth knowing.",
        "Every vehicle is different.",
        "We’ll help you understand yours.",
        "Can you help if I have already found a vehicle?",
        "Yes. Send us the auction lot or vehicle details. Our team reviews the available vehicle information, history and documentation before proceeding with bidding.",
        "Where do you source vehicles?",
        "We source vehicles from the USA, Europe and China. A manager can discuss available options, delivery destinations and arrangements for your specific vehicle.",
        "Do you work with automotive dealers?",
        "Yes. We support professional dealers with access to major US auctions, expert lot review, bidding, documentation and logistics. Individual partnership terms are discussed with a manager.",
        "How much will it cost, and how long does delivery take?",
        "Costs and timelines depend on the vehicle, its location and delivery arrangements. A manager will explain the specific costs, payment schedule and expected timeline for your inquiry.",
      ],
    },
    {
      title: "Inquiry form",
      keys: [
        "Not sure yet",
        "Dealer",
        "Private buyer",
        "Not provided",
        "Your inquiry could not be sent. Please try again.",
        "Could not connect. Please try again.",
        "Your next vehicle",
        "starts with a",
        "conversation.",
        "Have a vehicle in mind? An auction lot to check? Or just a few questions? Tell us where you’d like to start.",
        "For private buyers and professional dealers",
        "Clear guidance, from selection to delivery",
        "Your inquiry is on its way.",
        "Our team will contact you using the details you provided.",
        "Send another inquiry",
        "All fields are required unless marked optional.",
        "I’m looking for a vehicle as a",
        "Full name",
        "Your name",
        "Email address",
        "Phone",
        "(optional)",
        "Sourcing region",
        "What are you looking for?",
        "A make and model, your budget, or a link to an auction lot…",
        "Website",
        "Sending inquiry",
        "Send inquiry",
        "Prepare my inquiry",
        "Your details will be used to respond to this inquiry.",
        "Prepare a summary to share with our team. Online sending is not available yet.",
        "Your inquiry is ready.",
        "Download your summary and share it with your Logistic Hub contact. Nothing has been sent.",
        "Download inquiry",
        "VEHICLE INQUIRY",
        "Name",
        "Email",
        "Customer",
        "Region",
        "Vehicle requirements",
        "Please fill in this field.",
        "Enter a valid email address.",
        "Please enter at least 10 characters.",
      ],
    },
    {
      title: "Inquiry form: sending errors",
      keys: [
        "Please send your inquiry from this website.",
        "Your inquiry is too long.",
        "Please check your inquiry and try again.",
        "Your inquiry could not be accepted.",
        "Check your name, email and vehicle requirements, then try again.",
        "Online sending is not available yet. Please return to the form to prepare a downloadable inquiry.",
        "Your inquiry could not be sent. Your details are still in the form; please try again.",
        "Too many inquiries from this connection. Please wait a few minutes and try again.",
        "We are receiving too many inquiries right now. Please try again later.",
      ],
    },
    {
      title: "Thank-you page (after an inquiry is sent)",
      note: "The page also shows “Your inquiry is on its way.”, “Our team will contact you…”, “Send another inquiry” and the menu names “Cars from China” and “Fee calculator”, edited in their own sections.",
      keys: [
        "Thank you.",
        "While you wait",
        "See the cars we have selected in China, with clear prices and delivery to Tbilisi.",
        "Estimate Copart and IAAI fees before you bid.",
        "Looking for more than one vehicle? Tell us about the next one.",
      ],
    },
    {
      title: "Dealers page",
      keys: [
        "For automotive dealers",
        "Access leading US vehicle auctions with expert lot review, bidding support, documentation and logistics from Logistic Hub.",
        "A stronger partner.",
        "For your next",
        "move.",
        "Auction access, expert review and dependable logistics. Build your vehicle sourcing operation with a team that understands the business.",
        "Talk dealer opportunities",
        "Vehicles in an automotive showroom; illustrative photography",
        "Access the auctions.",
        "Keep the support.",
        "Logistic Hub gives professional dealers access to major US automotive auctions, including Copart, IAAI, Manheim, ADESA and other available platforms.",
        "Review of your selected lots before bidding",
        "Vehicle history and documentation checks",
        "Bidding after expert approval",
        "Logistics coordination with Lion Trans",
        "Regular updates until the vehicle is received",
        "Partnership terms, payment arrangements and documentation requirements are explained directly by a sales manager, based on your needs.",
      ],
    },
    {
      title: "Fee calculator",
      keys: [
        "Auction fees",
        "Estimate auction fees",
        "Auction fee calculator",
        "Estimate Copart and IAAI buyer, bid, gate and service fees on top of a winning bid, using each auction’s official schedule.",
        "Auction fees,",
        "before you bid.",
        "See what Copart and IAAI add to a winning bid. Choose the auction, enter your bid and get each fee from the auction’s official schedule.",
        "Auction",
        "Winning bid",
        "Title type",
        "Salvage or other non-clean",
        "Clean",
        "How the lot is won",
        "Live bid",
        "Pre-bid",
        "Estimated auction fees",
        "Buyer fee",
        "Live online bid fee",
        "Proxy bid fee",
        "Service fee",
        "Title handling fee",
        "Virtual bid fee",
        "Gate fee",
        "Environmental fee",
        "Bid plus auction fees",
        "Enter a winning bid to see the fees.",
        "Based on the official standard-vehicle schedule for payment by wire transfer.",
        "Checked",
        "View the Copart schedule",
        "View the IAAI schedule",
        "Not included: storage, late payment and title shipping fees, delivery from the US and customs clearance.",
        "Not included: IAA’s EH&S and fuel surcharge, storage, late payment and premium imagery fees, delivery from the US and customs clearance.",
        "Your manager confirms the final amount before you bid.",
        "These are the auction’s standard fees. Logistic Hub adds no markup to them.",
      ],
    },
    {
      title: "Cars from China: catalogue",
      keys: [
        "Cars from China,",
        "ready for the road.",
        "Cars we have selected in China, with clear prices and delivery to Tbilisi arranged by our team. New offers appear here as soon as we find them.",
        "Filters",
        "Make",
        "All makes",
        "Body type",
        "All body types",
        "Fuel type",
        "All fuel types",
        "Location",
        "Anywhere",
        "Price, USD",
        "From",
        "To",
        "Year",
        "Include sold cars",
        "Sort by",
        "Newest first",
        "Price: low to high",
        "Price: high to low",
        "Year: newest",
        "Mileage: lowest",
        "Show cars",
        "Clear filters",
        "Cars found:",
        "No cars are listed right now.",
        "No cars match these filters.",
        "New offers from China appear here as soon as we find them.",
        "Tell us what you’re looking for and we’ll search for you.",
        "Pages",
        "Previous page",
        "Next page",
      ],
    },
    {
      title: "Car page",
      keys: [
        "All cars",
        "Price on request",
        "Negotiable",
        "Ask about this car",
        "I’m interested in this car:",
        "Posted",
        "not visible to visitors",
        "Specifications",
        "Features",
        "Description",
        "Mileage",
        "Gearbox",
        "Drive",
        "Condition",
        "Engine volume",
        "Cylinders",
        "Power",
        "Battery capacity",
        "Range",
        "Doors",
        "Seats",
        "Steering wheel",
        "Color",
        "Interior color",
        "Interior material",
        "Airbags",
        "VIN",
        "km",
        "L",
        "hp",
        "kWh",
        "photo",
        "Previous photo",
        "Next photo",
        "Open full-screen photo",
        "Show photo",
        "Close",
      ],
    },
    {
      title: "Car listing options",
      keys: [
        "Draft",
        "Available",
        "Reserved",
        "Sold",
        "Sedan",
        "Hatchback",
        "SUV",
        "Crossover",
        "Wagon",
        "Coupe",
        "Convertible",
        "Minivan",
        "Pickup",
        "Van",
        "New",
        "Used",
        "Electric",
        "Plug-in hybrid",
        "Range extender (EREV)",
        "Hybrid",
        "Petrol",
        "Diesel",
        "LPG",
        "CNG",
        "Hydrogen",
        "Automatic",
        "Single-speed (EV)",
        "Robotised (DCT)",
        "CVT",
        "Tiptronic",
        "Manual",
        "Front-wheel drive",
        "Rear-wheel drive",
        "All-wheel drive (4×4)",
        "Left",
        "Right",
        "Black",
        "White",
        "Silver",
        "Grey",
        "Blue",
        "Light blue",
        "Green",
        "Red",
        "Maroon",
        "Orange",
        "Yellow",
        "Gold",
        "Beige",
        "Brown",
        "Purple",
        "Pink",
        "Other",
        "Leather",
        "Artificial leather",
        "Combined",
        "Fabric",
        "Alcantara",
        "In China",
        "In transit",
        "In Tbilisi",
        "Price in China",
        "Price in Tbilisi, customs not cleared",
        "Price in Tbilisi, customs cleared",
      ],
    },
    {
      title: "Car features",
      keys: [
        "Comfort",
        "Climate control",
        "Air conditioning",
        "Heated seats",
        "Ventilated seats",
        "Massage seats",
        "Electric seats",
        "Seat memory",
        "Heated steering wheel",
        "Multifunction steering wheel",
        "Keyless entry and start",
        "Cruise control",
        "Adaptive cruise control",
        "Electric windows",
        "Electric tailgate",
        "Sunroof",
        "Panoramic roof",
        "Air suspension",
        "Multimedia",
        "Navigation",
        "Bluetooth",
        "Apple CarPlay / Android Auto",
        "Digital instrument cluster",
        "Head-up display",
        "Wireless phone charging",
        "Premium audio",
        "Rear-seat screens",
        "Safety and assistance",
        "ABS",
        "Stability control (ESP)",
        "Central locking",
        "Alarm",
        "Parking sensors",
        "Rear-view camera",
        "360° camera",
        "Blind-spot monitoring",
        "Lane-keeping assist",
        "Automatic emergency braking",
        "Advanced driver assistance (L2)",
        "Automatic parking",
        "Tyre pressure monitoring",
        "LED headlights",
        "Other features",
        "Alloy wheels",
        "Spare wheel",
        "Tow bar",
        "Heat pump",
        "Vehicle-to-load (V2L)",
        "DC fast charging",
      ],
    },
  ];

export const textKeys = new Set(textSections.flatMap((s) => s.keys));
